### ISSUE TITLE
How do you change default shortcut keys?

### ISSUE THREAD

**Issue by sts10** [phamdaniel/mute-tab-chrome#1]
I assumed there would be a link to "options" in `chrome://extensions/` but I'm only seeing "Permissions" and "Details".

**Comment by danhp** [comment]
Its at the bottom of the page. :smile: 

![image](https://cloud.githubusercontent.com/assets/3745612/11852848/647e2fbe-a408-11e5-9f96-a53098d58779.png)

**Comment by dandaka** [comment]
I don't see it, do I miss something?

![mute-tab](https://cloud.githubusercontent.com/assets/2384694/15074347/c50f184c-139e-11e6-85ab-6eef09e56810.jpg)

**Comment by danhp** [comment]
This leverages Chrome's shortcut system to avoid injecting javascript into every single page, so the options for them are handled by Chrome. You're on the right page, they're just at the the very bottom of that (see the picture above).

**Comment by dandaka** [comment]
I got it. I was confused, that your screenshot has "options" link and mine don't.
