### ISSUE TITLE
Mute "radio" tabs/sites

### ISSUE THREAD

**Issue by dandaka** [phamdaniel/mute-tab-chrome#2]
## Background

There are a lot of "radio"-like websites, that people use to listen to. My examples include:

— Soundcloud
— Youtube
— FIP radio http://www.fipradio.fr/player
## Problem

When user encounter a website, that needs "radio" to be muted, there is no way to quickly do that.
## Possible solutions
1. Mute all except active tab shortcut
2. Mute all 'radio' websites

Second option is not that flexible, since sometime you would want to mute 'radio' Youtube video to listen to another Youtube video.

**Comment by danhp** [comment]
A solution for what you're proposing is already implemented. See:
![image](https://cloud.githubusercontent.com/assets/3745612/15074638/11be2876-136e-11e6-9d4b-8bed4e7adf5d.png)

**Comment by dandaka** [comment]
You rock, Daniel! 🚀

**Comment by dandaka** [comment]
![flags](https://cloud.githubusercontent.com/assets/2384694/15074973/57019966-13a2-11e6-834e-3362074c5d16.png)

A more recent screenshot for documentation
